- environment.yml
> Synchronize dependencies with requirements.txt

- roocs_utils/__init__.py
- roocs_utils/etc/roocs.ini
- roocs_utils/project_utils.py
- tests/test_project_utils.py
Added project name and base_dir functions and tests
> adding common functions and testing

- roocs_utils/etc/roocs.ini
- roocs_utils/project_utils.py
Updating dask environment variables - these are set in clisops - PR in clisops to follow
> Environment variables

- roocs_utils/xarray_utils/xarray_utils.py
- tests/test_xarray_utils/test_get_main_var.py
Fix for `get_main_var()` and some tests
> Main var issue

- roocs_utils/parameter/level_parameter.py
- roocs_utils/xarray_utils/xarray_utils.py
- tests/test_parameter/test_level_parameter.py
@ellesmith88: please check you are happy with this PR. I have made a few changes to implement the `LevelParameter` ready for clisops and daops to use.
> Fully implemented level parameter.

- HISTORY.rst
- MANIFEST.in
- docs/environment.yml
- setup.cfg
Fixed MANIFEST.in so that etc/roocs.ini is included for pip install.
Checked with test pypi and it is there
> Fix include of etc/roocs.ini

- roocs_utils/etc/roocs.ini
Edits the file name templates so that file names for datasets that do not have a time component don't end in an underscore
> edit file name templates

- roocs_utils/etc/roocs.ini
- roocs_utils/parameter/dimension_parameter.py
- roocs_utils/project_utils.py
- roocs_utils/xarray_utils/xarray_utils.py
- tests/test_parameter/test_dimension_parameter.py
Add dimension parameter for average operation. 
Edited file name template to allow extras
> Dimension parameter

- tests/conftest.py
Very minor fix - improving how test data is loaded with `GitPython`.
> Gitpython testdata fix

- roocs_utils/etc/roocs.ini
- roocs_utils/inventory/inventory.py
- roocs_utils/project_utils.py
Updated inventory to check maximum and minimum of latitude and longitude are within expected values
Checks the max and min - if either is nan, evaluates again using `float(coord.min())`
Also updated the doc strings on `roocs_utils.project_utils`
> Add bounds check to inventory for latitude and longitude

- .github/PULL_REQUEST_TEMPLATE.md
- AUTHORS.rst
- HISTORY.rst
- docs/configuration.rst
Updates to HISTORY.md for release 0.3.0
Added a pull request template as well.
> updates for release and add PR template

- .pre-commit-config.yaml
- roocs_utils/catalog_maker/batch.py
- roocs_utils/catalog_maker/catalog.py
- roocs_utils/catalog_maker/cli.py
- roocs_utils/etc/roocs.ini
- roocs_utils/exceptions.py
- roocs_utils/parameter/area_parameter.py
- roocs_utils/parameter/collection_parameter.py
- roocs_utils/parameter/dimension_parameter.py
- roocs_utils/parameter/level_parameter.py
- roocs_utils/parameter/time_parameter.py
- roocs_utils/project_utils.py
- tests/test_catalog_maker/test_catalog_maker.py
Some small changes to the catalogue maker:
- to create the correct number of batch files
- to solve an error when extracting the level data
- to create the batch files in the correct directory
- add a count of the number of datasets scanned as well as the number of files
> Catalog maker changes

- roocs_utils/catalog_maker/catalog.py
Update cache in intake catalogue, it will now be a list.
> update format of catalogue

- HISTORY.rst
- README.rst
- docs/installation.rst
- requirements_dev.txt
- roocs_utils/catalog_maker/database.py
Remove abcunit-backend and psycopg2 dependencies to allow easy pip install
> Release v0.4.1

- requirements.txt
Remove abcunit-backend from requirements.txt
> remove dependency

- setup.py
Fixes a broken link on PyPI.
Nope, it's a "fixing" change.
> Fix URL address

- docs/usage.rst
Remove text out of code block in docs
> update usage docs

- HISTORY.rst
- roocs_utils/config.py
- roocs_utils/etc/roocs.ini
- roocs_utils/project_utils.py
- tests/_common.py
- tests/test_project_utils.py
- tests/test_xarray_utils/test_cf_xarray.py
Additional feature
* **Does this PR introduce a breaking change?:**
No
See HISTORY.rst for details.
> Fixed path modifiers

- roocs_utils/parameter/base_parameter.py
- roocs_utils/parameter/level_parameter.py
- roocs_utils/parameter/param_utils.py
- roocs_utils/parameter/time_components_parameter.py
- roocs_utils/parameter/time_parameter.py
- tests/test_parameter/test_level_parameter.py
- tests/test_parameter/test_time_components_parameter.py
- tests/test_parameter/test_time_parameter.py
This PR updates the `subset-by-point` branch.
Changes:
* extended time and level parameter for string input (issue #89)
* added get_bounds for time_components_parameter (issue #90)
* updated tests
> Subset by point carsten

- roocs_utils/xarray_utils/xarray_utils.py
- tests/conftest.py
- tests/test_xarray_utils/test_get_coords.py
- This PR relates to https://github.com/roocs/catalog-maker/issues/11
> Update get coord by type

- roocs_utils/etc/roocs.ini
This PR updates the default `roocs.ini` config for c3s-cmip5 and c3s-cordex. 
It sets the default `data_node_root`.
> added data_node_root for c3s-cmip5 and c3s-cordex

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
> Prepare release 0.6.1

- roocs_utils/xarray_utils/xarray_utils.py
- tests/test_xarray_utils/test_get_coords.py
bug fix
no
* **Other information:** 
See PR in clisops https://github.com/roocs/clisops/pull/225
> fix get_coords_by_type to handle non existing coords

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
prepare release, updated HISTRORY.rst.
> Prepare release 0.6.2

- .github/workflows/main.yml
- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
- tests/test_xarray_utils/test_open_xr_dataset.py
Updated release notes for 0.6.3
> Prepare release 0.6.3

- .github/workflows/main.yml
- .readthedocs.yml
- environment.yml
- requirements.txt
- roocs_utils/utils/time_utils.py
- roocs_utils/xarray_utils/xarray_utils.py
- setup.py
feature
no. 
But change is needed by rook version >=0.11.0
> added "realization" to known coords

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
Updated `history.rst` for release 0.6.5.
> Prepare release 0.6.5

- roocs_utils/etc/roocs.ini
- tests/test_project_utils.py
This PR updates the default config `roocs.ini` for atlas datasets. It adds also some tests for the project-name discovery. 
> Add atlas config

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
This PR prepares the patch release 0.6.6.
> Prepare release 0.6.6

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
This PR prepares the patch release 0.6.7.
> Prepare release 0.6.7

- HISTORY.rst
- docs/conf.py
- roocs_utils/__init__.py
- setup.cfg
- setup.py
This PR prepares the patch release 0.6.9.
> Prep rel 0.6.9
